### ISSUE TITLE
一个微不足道的文字错误 ; )

### ISSUE THREAD

**Issue by sooxin** [stone0090/javascript-lessons#1]
### 一个微不足道的文字错误 ; )

---

1.1-Introduction 简介 中，在 **JavaScript 起源** 标题下最后一段文字：

> JavaScript 从一个简单的输入验证器发展成为一门强大的編程语言，完全出乎人们的意料。

其中的“編程语言”的“編”写成繁体了！（或见截图）
![js](https://cloud.githubusercontent.com/assets/16705366/17892568/91295066-6974-11e6-8d6a-a5996231a1dc.png)

希望作者改一下。
文章写得很棒，已关注微信，作者加油，期待更多精彩的文章！

**Comment by stone0090** [comment]
非常感谢指出不足，现已修复，如果您在阅读时有什么问题也可以随时与我交流。

**Comment by sooxin** [comment]
Okay (ง •̀_•́)ง
