### ISSUE TITLE
1.5章的挑战5应该怎么理解？

### ISSUE THREAD

**Issue by ljw-bigtail** [stone0090/javascript-lessons#12]
我理解的是先计算  b==c;  //false  ，然后 a = false;  ，但是这样的结果和  https://github.com/ljw-bigtail/javascript-lessons/blob/master/1.5-Expression%26Operators/Answer.md  中写的结果并不一样，请问这应该怎么理解？

var a,b,c;a=b==c;console.log(a);      // false

**Comment by stone0090** [comment]
你所理解的运算顺序没有问题，确实是先计算 `b==c;`，然后再把结果赋值给 `a`，但表达式 `b==c;` 的运算结果是 `true` 而不是 `false`。

我们首先定义了3个变量 `var a,b,c;`，因为它们均未赋值，所以默认值均为 `undefined`，所以表达式 `b==c;` 的计算结果是 `true`，然后 `a = true;`，所以最后 `console.log(a);` 输出也是为 `true`。

**Comment by ljw-bigtail** [comment]
明白了，谢谢你。
