### ISSUE TITLE
append() & appendChild()

### ISSUE THREAD

**Issue by CarmenWoo** [stone0090/javascript-lessons#18]
Hello Stone，使用代码里面document.body.append(div); 时无法插入div，改为appendChild后成功显示。
我的理解是因为append是jQuery的，在原生态JS代码里所以无法显示，需要改代码为document.body.appendChild(div);？不知道理解的对不对，学习JS中还是小白，请大神指教。

**Comment by stone0090** [comment]
不好意思，这里是笔误，正确的写法应该是 `appendChild `。
但是我在chrome下调试的时候，居然可以正常的运行，所以没有发现该问题，谢谢指出。
