### ISSUE TITLE
2.5原型一章调用方法书写错误

### ISSUE THREAD

**Issue by MAYDAY1993** [stone0090/javascript-lessons#21]
你好 在 [https://github.com/stone0090/javascript-lessons/tree/master/2.5-Prototype](url) 里 如下图所示的两处person都应为friend,写错了 望改正，截图如下
![image](https://cloud.githubusercontent.com/assets/14831051/20911708/d40cc7a0-bba4-11e6-9104-6e2bbfb498e1.png)

**Comment by stone0090** [comment]
谢谢指正。
