### ISSUE TITLE
博客地址打不开

### ISSUE THREAD

**Issue by Ale-cc** [stone0090/javascript-lessons#24]
“
扩展阅读「JavaScript 检测原始值、引用值、属性」
http://shijiajie.com/2016/06/20/javascript-maintainable-javascript-validate1/
扩展阅读「JavaScript 检测之 basevalidate.js」
http://shijiajie.com/2016/06/25/javascript-maintainable-javascript-basevalidatejs/
”
打开文章链接提示 找不到服务器 。

**Comment by stone0090** [comment]
近期服务器疏于维护，目前已经修复。但域名解析生效需要48小时。如果您继续访问，亦可用 jiegeshe.com,shisb.com,jialisi.net三个域名访问，都是指向同一博客地址的。
